services:
  flask-boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
    command: [ "./scripts/run.sh" ]
